language: generic

services:
  - docker

script:
  - docker pull matthijsbos/nerdrage-controller-dev:latest
  - "docker run --rm -t -v $(pwd):/workspace -w /workspace matthijsbos/nerdrage-controller-dev:latest platformio run"
  - "docker run --rm -t -v $(pwd):/workspace -w /workspace matthijsbos/nerdrage-controller-dev:latest platformio test"
