language: generic

services:
  - docker

script:
  - docker pull matthijsbos/nerdrage-controller-dev:latest
  - "docker run --rm -t -v $(pwd):/workspace -w /workspace matthijsbos/nerdrage-controller-dev:latest platformio run -e esp32doit-devkit-v1"
  - "docker run --rm -t -v $(pwd):/workspace -w /workspace matthijsbos/nerdrage-controller-dev:latest platformio test -e native"
