language: generic

services:
  - docker

script:
  - docker pull matthijsbos/nerdrage-controller-dev:latest
  - "docker run --rm -v $(pwd):/workspace -w /workspace -d matthijsbos/nerdrage-controller-dev:latest platformio run"
